version: "2"

services:
  server:
    image: gocd/gocd-server:v17.4.0
    ports:
      - "8153:8153"
      - "8154:8154"

  agent:
    image: gocd/gocd-agent-alpine-3.5:v17.4.0
    environment:
      - GO_SERVER_URL=server
    links:
      - server:server
