version: "3"

services:
  radarr:
    image: 'linuxserver/radarr'
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies
      - ./radarr/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      #- UMASK_SET=022 #optional
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
     # - RUN_OPTS=run options here #optional
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
