version: "2"

services:
  server:
    build: ./server
    links:
      - postgres:postgres
    ports:
      - "8080:8080"
      - "53:53"

  postgres:
    build: ./postgres

  worker:
    build: ./worker
    links:
      - server:server
      - postgres:postgres
    volumes_from:
      - server
    privileged: true
