version: "2"

services:
  server:
    build: ./server
    links:
      - postgres:postgres
    ports:
      - "2222:2222"
      - "8080:8080"

  postgres:
    build: ./postgres

  worker:
    build: ./worker
    links:
      - server:server
    volumes_from:
      - server
    privileged: true